/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bfst2023.handins;

import bfst2023.handins.model.Address;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class App extends Application {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        launch(args);
    }

    // @Override
    // public void start(Stage stage) throws Exception {
    //     stage.setTitle("Address Parsing");
    //     stage.getIcons().add(new Image("bfst2023/handins/images/logo.jpg"));

    //     BorderPane pane = new BorderPane();
    //     TextField textField = new TextField();
    //     TextArea textArea = new TextArea();
        
    //     pane.setTop(textField);
    //     pane.setCenter(textArea);

    //     textField.setOnAction(e -> {
    //         Address address = Address.parse(textField.getText());
    //         textArea.setText(address.toString());
    //     });
        
    //     Scene scene = new Scene(pane, 400, 100);
    //     stage.setScene(scene);

    //     stage.show();

    // }


    @Override
    public void start(Stage stage) throws Exception {
        try {
            Parent root = FXMLLoader.load(getClass().getResource("gui/home.fxml"));
            Scene scene = new Scene(root);
            
            String css = this.getClass().getResource("css/home.css").toExternalForm();
            scene.getStylesheets().add(css);

            stage.setTitle("BFST2023 - PhiVa's Address Parsing");
            stage.getIcons().add(new Image("bfst2023/handins/images/logo.jpg"));
            stage.setResizable(false);

            stage.setScene(scene);
            stage.show();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }









}
